var key = {
    webSiteName: "My store",
    footerMenuText: "Opciones",
    headerMenuText: "Opciones",
    btnContactText: "Contactanos",
    btnSaveLabel: "Guardar",
    btnShowFormabel: "Abrir formulario",
    btnCloseLabel: "Cerrar",
    uploadedImageMessage: "Imagen cargada",
    registerUploadedMessage: "Registro creado",
    registerUpdatedMessage: "Registro actualizado",
    sendEmailMessage: "Enviar un correo",
    notEmailFormForMobiles: "Formulario de correo no está disponible",
    enterNameForEmal: "Su nombre por favor",
    enterCommentForEmal: "Tu comentario",
    btnSendForEmailText: "Enviar",
    greetings: "Bienvenido a My store",
    credentialsErrorMessage: "Sus credenciales no son correctos",
    wellcomeUser: "Bienvenido ",
    loginOut: "Salir",
    adminMenuText: "Admini",
    aAdminProductsMenu: "Productos",
    aAdminCategoriesMenu: "Categorías",
    categoryListH1: "Lista de categorías",
    categoryDescriptionListTitle: "Descripción",
    showMoreMessage: "Mostrar +",
    prodModaldetailsName: "Nombre: ",
    prodModaldetailsPrice: "Precio: ₡",
    prodModaldetailsNotPrice: "Precio: ₡???",
    prodModaldetailsCallPhone: "Llamanos a: ",
    productAdminPage: "Productos",
    categoryAdminPage: "Categoría",
    productListH1: "Lista de productos",
    hideAndShowButtonMessage: "Mostrar formulario",
    addUpdateProducts: "Agregar/actualizar productos",
    addUpdateCategory: "Agregar/actualizar categories",
    updatingFormMessage: "Actualizando!",
    btnResetFormText: "Resetear formulario",
    categoryListH1: "Lista de categorías",
    showProductImage: "Mostrar imagen",
    showProductPriceMessageYes: "Mostrar precio: si",
    showProductPriceMessageNo: "Mostrar pricio: no",
    placeHolderProductId: "Id producto: ",
    placeHolderProductInventory: "Inventorio: ",
    placeHolderProductState: "Estado: ",
    placeHolderProductName: "Nombre producto",
    placeHolderProductPrice: "Precio producto",
    placeHolderProductDescription: "Descripción",
    selectProductCategoryMessage: "Seleccionar categoría",
    showProductPriceMessage: "Mostrar precio",
    creationdateMessage: "Fecha de creación",
    lastModificationMessage: "Última modificación",
    productStateMessage: "Estado del producto",
    chooseFileMessage: "Escoger imagen",
    uploadFileMessage: "Imagen cargada",
    btnProductPormSubmit: "Cargar",
    fileDeletedMessage: "Archivo eliminado",
    fileNotDeletedMessage: "Archivo no se eliminó",
    placeHolderCategoryName: "Nombre de categoría",
    categoryInActiveOption: "Inactivo",
    categoryActiveOption: "Activo",
    placeHolderCategoryDescription: "Descripción",
    categoryStateLabelMessage: "Estado de categoría",
    submitCategoryForm: "Cargar",
    addImageMessage: "Favor agregue una imagen",
    noDeleteCategoryWithRegMessage: "No se puede eliminar esta categoría porque tiene archivos asociados",
    thIdCategoryTable: "Id (código)",
    thNameCategoryTable: "Nombre",
    thStateCategoryTable: "Estado",
    thActionsCategoryTable: "Acciones",
    addPurchaseHeaderLabel: "Agregar una compra de",
    purchaseRecieptLabel: "Factura",
    purchaseUnitPriceLabel: "Pricio unitario",
    purchaseTottalUnitsLabel: "Total de unidades",
    purchasePaymentStateLabel: "Estado de la compra",
    purchaseDescriptionLabel: "Descripción de la compra",
    purchaseCreationDateLabel: "Fecha de creación",
    purchaseModificationDateLabel: "Última modificación",
    btnPurchaseSubmit: "Guardar",
    purchasePageHeader: "Agregar una compra de",
    createShortCutMessage: "Arrastra esta imagen al escritorio o a la marca de libro para crear un acceso directo",
    createShortCutTitle: "Crear un acceso directo para My store",
}
var pagesNames = {
    aloginText: "Ingresar",
    homeText: "Inicio",
    aboutText: "Acerca de nosotros",
    contactText: "Contactanos",
    storeText: "Tienda",
}
//new from the 85 line on
module.exports = {
    key: key,
    pagesNames: pagesNames
}